baseURL = "https://devloopsconsulting.com"
title = "DevLoops Consulting"
author = "DevLoops Consulting"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]
  showBlog = false
  mainSections = ['blog']
  googleFonts = true
  [params.logo]
    main = "img/devloops-logo-transparent.png"
    alt = "DevLoops Logo"
    size = "h-14"
  [params.site]
    name = "DevLoops Consulting"
  [params.icon]
    fontawesome = true
  [params.homepage_meta_tags]
    meta_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_og_title = "Tella"
    meta_og_type = "website"
    meta_og_url = "https://tella.pages.dev"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
#  [[menu.footer]]
#    name = "Home"
#    url = "/"
#      weight = 1

#  [[menu.footer]]
#    name = "Github"
#    url = "https://github.com/devloopsconsulting"
#    pre = "<i class='icon-github text-2xl'></i>"
#      weight = 2
